### ISSUE TITLE
Failed to run llvm optimizations

### ISSUE THREAD

**Issue by ricejasonf** [kripken/emscripten-fastcomp#186]
After upgrading from 1.37.2 to 1.37.13 I started getting the following linking error when running one of my tests:

```
/usr/local/bin/opt: CMakeFiles/individual.example.test.tiles.context.dir/context.cpp.o: error: Explicit load/store type does not match pointee type of pointer operand (Producer: 'LLVM4.0.0' Reader: 'LLVM 4.0.0')
Traceback (most recent call last):
  File "/usr/local/src/emscripten/em++", line 16, in <module>
    emcc.run()
  File "/usr/local/src/emscripten/emcc.py", line 1341, in run
    shared.Building.llvm_opt(temp_file, options.llvm_opts, new_temp_file)
  File "/usr/local/src/emscripten/tools/shared.py", line 1838, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
```

The debug output that precedes that is as follows:

```
DEBUG:root:PYTHON not defined in /root/.emscripten, using "/usr/bin/python"
DEBUG:root:Cache: PID 5943 acquiring multiprocess file lock to Emscripten cache
DEBUG:root:Cache: done
DEBUG:root:Cache: PID 5943 released multiprocess file lock to Emscripten cache
DEBUG:root:check tells us to use asm.js backend
WARNING:root:invocation: /usr/local/src/emscripten/em++ -DBOOST_HANA_CONFIG_ENABLE_STRING_UDL @CMakeFiles/individual.example.test.tiles.context.dir/includes_CXX.rsp -DNDEBUG -O2 -std=c++1z -ftemplate-backtrace-limit=0 -Wall -Wextra --bind -o CMakeFiles/individual.example.test.tiles.context.dir/context.cpp.o -c /opt/src/example/tiles/test/context.cpp --emscripten-cxx  (in /opt/build/example/tiles/test)
WARNING:root:Read response file CMakeFiles/individual.example.test.tiles.context.dir/includes_CXX.rsp: ['-I/opt/src/include', '-I/opt/src/example/tiles/test/../../../test/include']
DEBUG:root:compiling to bitcode
DEBUG:root:emcc step "parse arguments and setup" took 0.01 seconds
DEBUG:root:compiling source file: /opt/src/example/tiles/test/context.cpp
DEBUG:root:running: /usr/local/bin/clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=37 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/usr/local/src/emscripten/system/include/libcxx -Xclang -isystem/usr/local/src/emscripten/system/lib/libcxxabi/include -Xclang -isystem/usr/local/src/emscripten/system/include/compat -Xclang -isystem/usr/local/src/emscripten/system/include -Xclang -isystem/usr/local/src/emscripten/system/include/SSE -Xclang -isystem/usr/local/src/emscripten/system/include/libc -Xclang -isystem/usr/local/src/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/src/emscripten/system/local/include -DBOOST_HANA_CONFIG_ENABLE_STRING_UDL -I/opt/src/include -I/opt/src/example/tiles/test/../../../test/include -DNDEBUG -O2 -std=c++1z -ftemplate-backtrace-limit=0 -Wall -Wextra -c -mllvm -disable-llvm-optzns /opt/src/example/tiles/test/context.cpp -Xclang -isystem/usr/local/src/emscripten/system/include/SDL -emit-llvm -c -o CMakeFiles/individual.example.test.tiles.context.dir/context.cpp.o
DEBUG:root:emcc step "bitcodeize inputs" took 1.20 seconds
DEBUG:root:optimizing /opt/src/example/tiles/test/context.cpp
DEBUG:root:emcc: LLVM opts: -O3 -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false  [num inputs: 1]
```

I'm sorry that I am unable to make a minimal test case. If I could find whatever code is causing this I would probably try to work around it assuming there is no way to fix this.

Any help is greatly appreciated.

**Comment by kripken** [comment]
Strange error. One guess is that it's newer LLVM failing to handle older bitcode. Are you perhaps compiling in a library built with an older version of emscripten? Also I'd make sure to do `emcc --clear-cache --clear-ports` to ensure all system libs are rebuilt.

**Comment by ricejasonf** [comment]
Thanks for the reply.

I'm using docker to build the whole system from scratch. I was cloning the `incoming` branches as is shown in my script below, but I am currently retrying with explicitly specifying the tag to see if I can pinpoint the version where this starts happening (assuming it is not an error on my end)

Here is my Dockerfile script if you are curious:

```dockerfile
FROM ricejasonf/cppdock
MAINTAINER Jason Rice

RUN apt-get update && apt-get -y install \
  python default-jre-headless curl tar xz-utils build-essential

WORKDIR /usr/local/src

# node
RUN curl -O https://nodejs.org/dist/v6.9.5/node-v6.9.5-linux-x64.tar.xz \
  && tar -xvf node-v6.9.5-linux-x64.tar.xz \
  && cp -r node-v6.9.5-linux-x64/* /usr/local/ \
  && rm -f node-v6.9.5-linux-x64.tar.xz \
  && rm -rf node-v6.9.5-linux-x64

# clang w/emscripten
RUN git clone -b incoming https://github.com/kripken/emscripten.git \
  && git clone -b incoming https://github.com/kripken/emscripten-fastcomp.git \
  && cd emscripten-fastcomp/tools/ \
  && git clone -b incoming https://github.com/kripken/emscripten-fastcomp-clang.git clang \
  && cd ../projects \
  && git clone https://github.com/llvm-mirror/libcxx.git \
  && git clone https://github.com/llvm-mirror/libcxxabi.git \
  && cd ../ && mkdir build && cd build \
  && cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DLLVM_TARGETS_TO_BUILD="X86;ARM;JSBackend" \
    -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF \
    -DCLANG_INCLUDE_EXAMPLES=OFF -DCLANG_INCLUDE_TESTS=OFF \
    .. \
  && make -j4 && make install \
  && cd /usr/local/src && rm -rf ./emscripten-fastcomp

RUN cd /usr/local/src/emscripten && ./emcc -v \
    && ./em++ ./tests/hello_world.cpp \
    && ./em++ ./tests/hello_libcxx.cpp

ENV CC=/usr/local/bin/clang \
    CXX=/usr/local/bin/clang++ \
    LD_LIBRARY_PATH=/usr/local/lib
```

**Comment by ricejasonf** [comment]
Its starts doing it at 1.37.7, but I'm not sure how I can narrow down a test case or anything.

**Comment by kripken** [comment]
1.37.7 did indeed bring in a new LLVM version. So if you're sure you're not somehow processing older LLVM bitcode, perhaps you are hitting an LLVM bug. You can test your project on plain LLVM 4.0 and see if it reproduces there.

**Comment by ricejasonf** [comment]
It appears to be unique to emscripten. I don't get any error with the same compiler targeting `X86`.

**Comment by kripken** [comment]
Is that checked with bitcode (to fully parallel emcc), or native object files?

**Comment by ricejasonf** [comment]
> Is that checked with bitcode (to fully parallel emcc), or native object files?

I'm not sure what you mean. I am just using em++ on a header only library so I think it is all bitcode.

I think I narrowed it down to a somewhat minimal test case. With the following I get an odd linker error:

```cpp
#include <array>

struct foo {
	int x;
	std::array<unsigned char, 5> bar;
};

struct get
{
	template <typename T>
	static constexpr auto apply(T)
	{
		return foo({42, {{0, 1, 2, 3, 4}}});
	}
};

int main()
{
	get::apply(5);
}
```

Linker Error:
```
root@775787bdf1f8:/opt/build# /usr/local/src/emscripten/em++ --std=c++1z ftest.cpp
/usr/local/bin/opt: error loading file '/tmp/tmpuGExHN/ftest_0.o'
Traceback (most recent call last):
  File "/usr/local/src/emscripten/em++", line 16, in <module>
    emcc.run()
  File "/usr/local/src/emscripten/emcc.py", line 1642, in run
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/usr/local/src/emscripten/tools/shared.py", line 1838, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
```

But if the `std::array` is larger than my initializer list it explodes with an internal compiler error:
```cpp
#include <array>

struct foo {
	int x;
	std::array<unsigned char, 6> bar;
};

struct get
{
	template <typename T>
	static constexpr auto apply(T)
	{
		return foo({42, {{0, 1, 2, 3, 4}}});
	}
};

int main()
{
	get::apply(5);
}
```
Ouptut:
```
root@775787bdf1f8:/opt/build# /usr/local/src/emscripten/em++ --std=c++1z ftest.cpp 
#0 0x000055fff36c9d48 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/local/bin/clang-4.0+0x13c4d48)
#1 0x000055fff36c7c6e llvm::sys::RunSignalHandlers() (/usr/local/bin/clang-4.0+0x13c2c6e)
#2 0x000055fff36c7daa SignalHandler(int) (/usr/local/bin/clang-4.0+0x13c2daa)
#3 0x00007f893047d670 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11670)
#4 0x000055fff2a1ac05 (anonymous namespace)::ArrayExprEvaluator::VisitInitListExpr(clang::InitListExpr const*) (/usr/local/bin/clang-4.0+0x715c05)
#5 0x000055fff4db8f64 clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::ArrayExprEvaluator, bool>::Visit(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x2ab3f64)
#6 0x000055fff4db96ec EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) [clone .constprop.1953] (/usr/local/bin/clang-4.0+0x2ab46ec)
#7 0x000055fff2a27453 (anonymous namespace)::RecordExprEvaluator::VisitInitListExpr(clang::InitListExpr const*) (/usr/local/bin/clang-4.0+0x722453)
#8 0x000055fff4dd2a9a clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x2acda9a)
#9 0x000055fff4db9674 EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) [clone .constprop.1953] (/usr/local/bin/clang-4.0+0x2ab4674)
#10 0x000055fff2a27453 (anonymous namespace)::RecordExprEvaluator::VisitInitListExpr(clang::InitListExpr const*) (/usr/local/bin/clang-4.0+0x722453)
#11 0x000055fff4dd2a9a clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x2acda9a)
#12 0x000055fff2a26afd (anonymous namespace)::ExprEvaluatorBase<(anonymous namespace)::RecordExprEvaluator>::VisitCastExpr(clang::CastExpr const*) (/usr/local/bin/clang-4.0+0x721afd)
#13 0x000055fff2a26c57 (anonymous namespace)::RecordExprEvaluator::VisitCastExpr(clang::CastExpr const*) (/usr/local/bin/clang-4.0+0x721c57)
#14 0x000055fff4dd2cde clang::StmtVisitorBase<clang::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) (/usr/local/bin/clang-4.0+0x2acdcde)
#15 0x000055fff4dbcb2c Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) (/usr/local/bin/clang-4.0+0x2ab7b2c)
#16 0x000055fff4dbe7e1 EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) (/usr/local/bin/clang-4.0+0x2ab97e1)
#17 0x000055fff4dbeaba clang::Expr::EvaluateAsRValue(clang::Expr::EvalResult&, clang::ASTContext const&) const [clone .part.1920] (/usr/local/bin/clang-4.0+0x2ab9aba)
#18 0x000055fff4dbebbe clang::Expr::EvaluateAsRValue(clang::Expr::EvalResult&, clang::ASTContext const&) const (/usr/local/bin/clang-4.0+0x2ab9bbe)
#19 0x000055fff4dbf023 clang::Expr::isEvaluatable(clang::ASTContext const&, clang::Expr::SideEffectsKind) const (/usr/local/bin/clang-4.0+0x2aba023)
#20 0x000055fff388bb99 clang::CodeGen::CodeGenFunction::EmitReturnStmt(clang::ReturnStmt const&) (/usr/local/bin/clang-4.0+0x1586b99)
#21 0x000055fff388d83f clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/usr/local/bin/clang-4.0+0x158883f)
#22 0x000055fff38b18c8 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::CodeGen::FunctionArgList&, clang::Stmt const*) (/usr/local/bin/clang-4.0+0x15ac8c8)
#23 0x000055fff38ba975 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/usr/local/bin/clang-4.0+0x15b5975)
#24 0x000055fff38d3955 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/bin/clang-4.0+0x15ce955)
#25 0x000055fff38e41ce clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/bin/clang-4.0+0x15df1ce)
#26 0x000055fff38e437e clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/bin/clang-4.0+0x15df37e)
#27 0x000055fff38e4454 clang::CodeGen::CodeGenModule::Release() (/usr/local/bin/clang-4.0+0x15df454)
#28 0x000055fff3eae557 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) (/usr/local/bin/clang-4.0+0x1ba9557)
#29 0x000055fff3eadde5 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/bin/clang-4.0+0x1ba8de5)
#30 0x000055fff4277f98 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clang-4.0+0x1f72f98)
#31 0x000055fff3b8cffe clang::FrontendAction::Execute() (/usr/local/bin/clang-4.0+0x1887ffe)
#32 0x000055fff3b5e736 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/bin/clang-4.0+0x1859736)
#33 0x000055fff3c14832 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/bin/clang-4.0+0x190f832)
#34 0x000055fff2a7fd50 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/bin/clang-4.0+0x77ad50)
#35 0x000055fff2a338f2 main (/usr/local/bin/clang-4.0+0x72e8f2)
#36 0x00007f892f6173f1 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f1)
#37 0x000055fff2a7ddba _start (/usr/local/bin/clang-4.0+0x778dba)
Stack dump:
0.	Program arguments: /usr/local/bin/clang-4.0 -cc1 -triple asmjs-unknown-emscripten -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name ftest.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -no-integrated-as -mconstructor-aliases -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /tmp/tmphsW0_s/ftest_0.gcno -nostdsysteminc -nobuiltininc -resource-dir /usr/local/bin/../lib/clang/4.0.0 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=37 -D __EMSCRIPTEN_tiny__=7 -D _LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration --std=c++1z -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir /opt/build -ferror-limit 19 -fmessage-length 95 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fdiagnostics-show-option -nobuiltininc -nostdsysteminc -isystem/usr/local/src/emscripten/system/include/libcxx -isystem/usr/local/src/emscripten/system/lib/libcxxabi/include -isystem/usr/local/src/emscripten/system/include/compat -isystem/usr/local/src/emscripten/system/include -isystem/usr/local/src/emscripten/system/include/SSE -isystem/usr/local/src/emscripten/system/include/libc -isystem/usr/local/src/emscripten/system/lib/libc/musl/arch/emscripten -isystem/usr/local/src/emscripten/system/local/include -isystem/usr/local/src/emscripten/system/include/SDL -o /tmp/tmphsW0_s/ftest_0.o -x c++ ftest.cpp 
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	ftest.cpp:11:24: Generating code for declaration 'get::apply'
clang-4.0: error: unable to execute command: Segmentation fault (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (https://github.com/kripken/emscripten-fastcomp-clang.git fc3b410c30c4818947365376d72f934e3767508d) (https://github.com/kripken/emscripten-fastcomp.git 00da98bb8e7173c946db9f706a0272f78c800ac9) (emscripten 1.37.7 : 1.37.7)
Target: asmjs-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /tmp/ftest-71da6a.cpp
clang-4.0: note: diagnostic msg: /tmp/ftest-71da6a.sh
clang-4.0: note: diagnostic msg: 

********************
```

**Comment by ricejasonf** [comment]
I managed to reproduce this with vanilla clang so I'll just submit the bug to them.

Thank you for your time. :sweat_smile:

**Comment by kripken** [comment]
Interesting, I wonder what's going on there. Please link the upstream bug if you can.

**Comment by ricejasonf** [comment]
https://bugs.llvm.org/show_bug.cgi?id=33288 :smile:

**Comment by kripken** [comment]
Thanks!
